version: '3.8'

services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: myadb
      MYSQL_USER: joe
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
        #host:container
      - 5000:3306
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data: