version: '3.8'

services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
        #host:container
      - 5000:3306
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
  #for data to persist. The data live as long as docker lives.
    name: mydata

# pull the image
# docker run -d -p 5000:3306 --name my-container -v mydata:/var/lib/mysql josepholmez/mysql