#application.yml
#Connecting with the MySQL Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mya
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#Port number
server:
  port: 5000

#Log location
logging:
  file:
    name: C:/logs/myapp.log
###############################################################################
#We can use application.properties insteed                                    #
#*application.properties#######################################################
# #MySQL Configuration                                                        #
# spring.datasource.driverClassName=com.mysql.jdbc.Driver                     #
# spring.datasource.url=jdbc:mysql://localhost:3306/mya                     #
# spring.datasource.username=root                                             #
# spring.datasource.password=1234                                             #
#                                                                             #
# spring.jpa.show-sql=true                                                    #
# spring.jpa.hibernate.ddl-auto=update                                        #
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect #
#                                                                             #
# #Thymeleaf                                                                  #
# spring.thymeleaf.cache=false                                                #
# spring.thymeleaf.suffix: .html                                              #
###############################################################################
