package com.olmez.mya.model.enums;

import org.checkerframework.checker.nullness.qual.Nullable;

import lombok.Getter;

@Getter
public enum CurrencyCode {
    AUD("AUD", "Australian dollar"),
    CAD("CAD", "Canadian dollar"),
    CHF("CHF", "Swiss franc"),
    EUR("EUR", "Euro"),
    GBP("GBP", "Pound sterling"),
    JPY("JPY", "Japanese yen"),
    RUB("RUB", "Russian ruble"),
    TRY("TRY", "Turkish lira"),
    USD("USD", "United States dollar"),
    AED("United Arab Emirates dirham"),
    AFN("Afghan afghani"),
    ALL("Albanian lek"),
    AMD("Armenian dram"),
    ANG("Netherlands Antillean guilder"),
    AOA("Angolan kwanza"),
    ARS("Argentine peso"),
    AWG("Aruban florin"),
    AZN("Azerbaijani manat"),
    BAM("Bosnia and Herzegovina convertible mark"),
    BBD("Barbadian dollar"),
    BDT("Bangladeshi taka"),
    BGN("Bulgarian lev"),
    BHD("Bahraini dinar"),
    BIF("Burundian franc"),
    BND("Brunei dollar"),
    BOB("Bolivian boliviano"),
    BRL("Brazilian real"),
    BSD("Bahamian dollar"),
    BWP("Botswana pula"),
    BYN("Belarusian ruble"),
    BZD("Belize dollar"),
    CDF("Congolese franc"),
    CLP("Chilean peso"),
    CNY("Renminbi"),
    COP("Colombian peso"),
    CRC("Costa Rican colón"),
    CUP("Cuban peso"),
    CVE("Cape Verdean escudo"),
    CZK("Czech koruna"),
    DJF("Djiboutian franc"),
    DKK("Danish krone"),
    DOP("Dominican peso"),
    DZD("Algerian dinar"),
    EGP("Egyptian pound"),
    ERN("Eritrean nakfa"),
    ETB("Ethiopian birr"),
    FJD("Fijian dollar"),
    GEL("Georgian lari"),
    GHS("Ghanaian cedi"),
    GIP("Gibraltar pound"),
    GMD("Gambian dalasi"),
    GNF("Guinean franc"),
    GTQ("Guatemalan quetzal"),
    GYD("Guyanese dollar"),
    HKD("Hong Kong dollar"),
    HNL("Honduran lempira"),
    HRK("Croatian kuna"),
    HTG("Haitian gourde"),
    HUF("Hungarian forint"),
    IDR("Indonesian rupiah"),
    ILS("Israeli new shekel"),
    INR("Indian rupee"),
    IQD("Iraqi dinar"),
    IRR("Iranian rial"),
    ISK("Icelandic króna"),
    JMD("Jamaican dollar"),
    JOD("Jordanian dinar"),
    KES("Kenyan shilling"),
    KGS("Kyrgyzstani som"),
    KHR("Cambodian riel"),
    KMF("Comorian franc"),
    KRW("South Korean won"),
    KWD("Kuwaiti dinar"),
    KZT("Kazakhstani tenge"),
    LAK("Lao kip"),
    LBP("Lebanese pound"),
    LKR("Sri Lankan rupee"),
    LRD("Liberian dollar"),
    LSL("Lesotho loti"),
    LYD("Libyan dinar"),
    MAD("Moroccan dirham"),
    MDL("Moldovan leu"),
    MGA("Malagasy ariary"),
    MKD("Macedonian denar"),
    MMK("Burmese kyat"),
    MNT("Mongolian tögrög"),
    MOP("Macanese pataca"),
    MRU("Mauritanian ouguiya"),
    MUR("Mauritian rupee"),
    MVR("Maldivian rufiyaa"),
    MWK("Malawian kwacha"),
    MXN("Mexican peso"),
    MYR("Malaysian ringgit"),
    MZN("Mozambican metical"),
    NAD("Namibian dollar"),
    NGN("Nigerian naira"),
    NIO("Nicaraguan córdoba"),
    NOK("Norwegian krone"),
    NPR("Nepalese rupee"),
    NZD("New Zealand dollar"),
    OMR("Omani rial"),
    PAB("Panamanian balboa"),
    PEN("Peruvian sol"),
    PGK("Papua New Guinean kina"),
    PHP("Philippine peso"),
    PKR("Pakistani rupee"),
    PLN("Polish złoty"),
    PYG("Paraguayan guaraní"),
    QAR("Qatari riyal"),
    RON("Romanian leu"),
    RSD("Serbian dinar"),
    RWF("Rwandan franc"),
    SAR("Saudi riyal"),
    SBD("Solomon Islands dollar"),
    SCR("Seychellois rupee"),
    SDG("Sudanese pound"),
    SEK("Swedish krona"),
    SGD("Singapore dollar"),
    SLL("Sierra Leonean leone"),
    SOS("Somali shilling"),
    SRD("Surinamese dollar"),
    SSP("South Sudanese pound"),
    STN("São Tomé and Príncipe dobra"),
    SVC("Salvadoran colón"),
    SYP("Syrian pound"),
    SZL("Swazi lilangeni"),
    THB("Thai baht"),
    TJS("Tajikistani somoni"),
    TMT("Turkmenistan manat"),
    TND("Tunisian dinar"),
    TOP("Tongan paʻanga"),
    TTD("Trinidad and Tobago dollar"),
    TWD("New Taiwan dollar"),
    TZS("Tanzanian shilling"),
    UAH("Ukrainian hryvnia"),
    UGX("Ugandan shilling"),
    UYU("Uruguayan peso"),
    UZS("Uzbekistani soʻm"),
    VES("Venezuelan bolívar"),
    VND("Vietnamese đồng"),
    VUV("Vanuatu vatu"),
    WST("Samoan tālā"),
    XAF("Central African CFA franc"),
    XAG("Silver (troy ounce)"),
    XAU("Gold (troy ounce)"),
    XCD("Eastern Caribbean dollar"),
    XDR("Special drawing rights"),
    XOF("West African CFA franc"),
    XPF("CFP franc"),
    YER("Yemeni rial"),
    ZAR("South African rand"),
    ZMW("Zambian kwacha"),
    JEP("Jersey pound"),
    GGP("Guernsey pound"),
    IMP("Manx pound"),
    FKP("Falkland Islands pound"),
    CUC("Cuban convertible peso"),
    SHP("Saint Helena pound"),
    ZWL("Zimbabwean dollar"),
    KYD("Cayman Islands dollar"),
    BMD("Bermudian dollar"),
    BTN("Bhutanese ngultrum");

    private @Nullable String code;
    private String name;

    private CurrencyCode(String name) {
        this(name, null);
    }

    private CurrencyCode(@Nullable String code, String name) {
        this.code = code;
        this.name = name;
    }

    @Override
    public String toString() {
        return code;
    }

}
